### ISSUE TITLE
any samples to enable private to true

### ISSUE THREAD

**Issue by ozbillwang** [haw-itn/serverless-web-monitor#1]
In part of 

```
custom:
  stage: ${opt:stage, self:provider.stage}
  func_prefix: ${self:service}-${self:custom.stage}
  private: false # Change to 'true' if you don't want to publish Dashboard
```
After enable private to true, could you please provide some samples on how to set the api keys:
```
   apiKeys:
     - some-api-key-name   # ???
```
What should I adjust when accessing the endpoint? How does the new curl url look like?

**Comment by ozbillwang** [comment]
I can answer my own question:

https://serverless.com/framework/docs/providers/aws/events/apigateway/

```
provider:
  name: aws
  apiKeys:
    - myFirstKey
    - ${opt:stage}-myFirstKey
    - ${env:MY_API_KEY}
```

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-apikey.html

After enabled, you need to add extra header `x-api-key` to access the site:

    curl  -H "x-api-key: HmClkBybt69H1WsNXUta52sgdLfMy5jK5brwVxGu"  https://xxxxxxxxx.execute-api.ap-northeast-1.amazonaws.com/dev/sites
